"""Update Vote and Model_Timespans models

Revision ID: 2ae59ca97166
Revises: 8d4af0596c87
Create Date: 2024-12-08 16:30:27.289330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae59ca97166'
down_revision = '8d4af0596c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model__timespans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_proposition', sa.String(), nullable=True))

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_comment', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('timespan_id', sa.Integer(), nullable=True))
        batch_op.alter_column('user_vote',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
        batch_op.create_foreign_key('fk_vote_timespan_id', 'model__timespans', ['timespan_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_vote',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('timespan_id')
        batch_op.drop_column('user_comment')

    with op.batch_alter_table('model__timespans', schema=None) as batch_op:
        batch_op.drop_column('model_proposition')

    # ### end Alembic commands ###
