"""Removing ECGSegment (redundant), adding User/Model_Timespans

Revision ID: 8d4af0596c87
Revises: 5f89da2f24af
Create Date: 2024-11-04 14:05:19.886006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4af0596c87'
down_revision = '5f89da2f24af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model__timespans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_timespan_start', sa.Float(), nullable=False),
    sa.Column('model_timespan_end', sa.Float(), nullable=False),
    sa.Column('chart_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['chart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user__timespans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_timespan_start', sa.Float(), nullable=False),
    sa.Column('user_timespan_end', sa.Float(), nullable=False),
    sa.Column('chart_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['chart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ecg_segment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecg_segment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('start_time', sa.FLOAT(), nullable=False),
    sa.Column('end_time', sa.FLOAT(), nullable=False),
    sa.Column('json_file_path', sa.VARCHAR(), nullable=False),
    sa.Column('chart_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['chart_id'], ['chart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user__timespans')
    op.drop_table('model__timespans')
    # ### end Alembic commands ###
